version: '3'

services:
  postgres:
    image: 'postgres:9.6-alpine'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=MATB09
      - POSTGRES_PASSWORD=MATB09
      - POSTGRES_DB=sisfila

  cassandra:
    image: 'cassandra:4.1'
    ports:
      - '7000:7000'
      - '7001:7001'
      - '7199:7199'
      - '9042:9042'
      - '9160:9160'
    # volumes:
      # - './cassandra.yaml:/etc/cassandra/cassandra.yaml'


volumes:
  postgres_data:
    driver: local
